Repository hmrc/amls, pull requests merged in 2018-10, with the labels that each got.

#204 Amls 4330 fix remaining tests
  test/controllers/SubscriptionViewControllerSpec.scala
  test/models/des/AmendVariationRequestSpec.scala
  test/models/des/SubscriptionRequestSpec.scala
  test/models/fe/SubscriptionViewSpec.scala
Labels: pending review

#210 Amls 4330 rebase
  .DS_Store
  app/controllers/SubscriptionViewController.scala
  app/models/Fees.scala
  app/models/des/AmendVariationResponse.scala
  app/models/des/SubscriptionResponse.scala
  app/models/des/responsiblepeople/ResponsiblePersons.scala
  app/models/fe/AmendVariationResponse.scala
  app/models/fe/SubscriptionFees.scala
  app/models/fe/SubscriptionResponse.scala
  app/models/fe/SubscriptionView.scala
  app/models/fe/responsiblepeople/ApprovalFlags.scala
  app/models/fe/responsiblepeople/DateOfBirth.scala
  app/models/fe/responsiblepeople/ResponsiblePeople.scala
  app/services/AmendVariationService.scala
  app/services/SubscriptionService.scala
  conf/.DS_Store
  conf/resources/api4_schema_release_3.0.0.json
  conf/resources/api6_schema_release_3.0.0.json
  test/controllers/FeesControllerSpec.scala
  test/controllers/SubscriptionViewControllerSpec.scala
  test/models/DefaultDesValues.scala
  test/models/DefaultFEValues.scala
  test/models/des/AmendVariationRequestSpec.scala
  test/models/des/AmendVariationResponseSpec.scala
  test/models/des/DesConstants.scala
  test/models/des/FeesSpec.scala
  test/models/des/SubscriptionRequestSpec.scala
  test/models/des/SubscriptionResponseSpec.scala
  test/models/des/responsiblepeople/ResponsiblePersonsSpec.scala
  test/models/fe/AmendVariationResponseSpec.scala
  test/models/fe/SubscriptionViewSpec.scala
  test/models/fe/responsiblepeople/ResponsiblePeopleSpec.scala
  test/services/AmendVariationServiceSpec.scala
  test/services/SubscriptionServiceSpec.scala
Labels: build passing, pending review

#212 Amls 4430 dob fix
  app/models/des/responsiblepeople/NonUkResident.scala
  app/models/fe/responsiblepeople/DateOfBirth.scala
  test/models/des/DesConstants.scala
  test/models/des/responsiblepeople/NationalityDetailsSpec.scala
  test/models/des/responsiblepeople/NonUkResidentSpec.scala
  test/models/fe/responsiblepeople/DateOfBirthSpec.scala
  test/models/fe/responsiblepeople/NonUKPassportSpec.scala
  test/models/fe/responsiblepeople/PersonResidenceTypeSpec.scala
  test/models/fe/responsiblepeople/ResidenceTypeSpec.scala
  test/models/fe/responsiblepeople/UKPassportSpec.scala
Labels: build passing, pending QA, pending review

#215 Amls 4446
  app/models/fe/SubscriptionView.scala
  test/models/fe/SubscriptionViewSpec.scala
Labels: pending QA, pending review

#217 Added more verbose logging for API 4 and 6
  app/audit/SubscriptionEvent.scala
  app/services/AmendVariationService.scala
  app/services/SubscriptionService.scala
Labels: pending QA, pending review

#213 Amls 4358
  app/models/Fees.scala
  app/models/des/AmendVariationResponse.scala
  app/models/des/SubscriptionResponse.scala
  app/models/fe/AmendVariationResponse.scala
  app/models/fe/SubscriptionFees.scala
  app/models/fe/SubscriptionResponse.scala
  app/models/fe/SubscriptionView.scala
  app/services/AmendVariationService.scala
  app/services/SubscriptionService.scala
  test/controllers/FeesControllerSpec.scala
  test/models/des/AmendVariationResponseSpec.scala
  test/models/des/FeesSpec.scala
  test/models/des/SubscriptionResponseSpec.scala
  test/models/fe/AmendVariationResponseSpec.scala
  test/models/fe/SubscriptionViewSpec.scala
  test/services/SubscriptionServiceSpec.scala
Labels: build passing
