Repository hmrc/amls, pull requests merged in 2019-06, with the labels that each got.

#260 Amls 4746 - phase-2-toggle removal
  app/config/AmlsConfig.scala
  app/models/des/responsiblepeople/NationalityDetails.scala
  app/models/des/responsiblepeople/ResponsiblePersons.scala
  app/models/fe/AmendVariationResponse.scala
  app/models/fe/SubscriptionResponse.scala
  app/models/fe/responsiblepeople/DateOfBirth.scala
  app/models/fe/responsiblepeople/ResponsiblePeople.scala
  app/services/AmendVariationService.scala
  app/services/SubscriptionService.scala
  conf/application.conf
  release_notes/AMLS-4746.txt
  test/controllers/SubscriptionViewControllerSpec.scala
  test/models/des/AmendVariationRequestSpec.scala
  test/models/des/SubscriptionRequestSpec.scala
  test/models/des/SubscriptionResponseSpec.scala
  test/models/des/responsiblepeople/NationalityDetailsSpec.scala
  test/models/des/responsiblepeople/ResponsiblePersonsSpec.scala
  test/models/fe/AmendVariationResponseSpec.scala
  test/models/fe/SubscriptionViewSpec.scala
  test/models/fe/responsiblepeople/DateOfBirthSpec.scala
  test/models/fe/responsiblepeople/ResponsiblePeopleSpec.scala
Labels: build passing

#261 Refactor Fee Response Controller to use DI
  app/controllers/FeeResponseController.scala
  app/modules/Module.scala
  app/repositories/FeesRepository.scala
  conf/app.routes
  test/controllers/FeesControllerSpec.scala
Labels: pending review

#262 AMLS-5022
  app/controllers/AmendVariationController.scala
  app/controllers/DeregisterSubscriptionController.scala
  app/controllers/FeeResponseController.scala
  app/controllers/PaymentController.scala
  app/controllers/RegistrationDetailsController.scala
  app/controllers/SubscriptionController.scala
  app/controllers/SubscriptionStatusController.scala
  app/controllers/SubscriptionViewController.scala
  app/controllers/WithdrawSubscriptionController.scala
  app/utils/DefaultAuthAction.scala
  conf/application.conf
  project/MicroServiceBuild.scala
  release_notes/AMLS-5022.txt
  test/controllers/AmendVariationControllerSpec.scala
  test/controllers/DeregisterSubscriptionControllerSpec.scala
  test/controllers/FeeResponseControllerSpec.scala
  test/controllers/PaymentControllerSpec.scala
  test/controllers/RegistrationDetailsControllerSpec.scala
  test/controllers/SubscriptionControllerSpec.scala
  test/controllers/SubscriptionStatusControllerSpec.scala
  test/controllers/SubscriptionViewControllerSpec.scala
  test/controllers/WithdrawSubscriptionControllerSpec.scala
  test/utils/AuthActionHelper.scala
Labels: pending QA

#264 AMLS-5022 | Added missing import
  app/controllers/SubscriptionController.scala
Labels: pending review
