Repository hmrc/amls, pull requests merged in 2019-03, with the labels that each got.

#240 Specify play http parser max memory buffer in line with DES limit
  conf/application.conf
  release_notes/AMLS-4775.txt
Labels: reviewed

#239 Amls 4272 - Supervision Section page split
  app/models/fe/supervision/AnotherBody.scala
  release_notes/AMLS-4272.txt
  test/models/fe/supervision/AnotherBodySpec.scala
Labels: pending QA, reviewed

#242 Amls 4756
  app/models/des/AmendVariationRequest.scala
  app/models/des/SubscriptionRequest.scala
  app/models/des/aboutthebusiness/Address.scala
  app/models/des/aboutthebusiness/AlternativeAddress.scala
  app/models/des/aboutthebusiness/BusinessContactDetails.scala
  app/models/des/aboutthebusiness/CorporationTaxRegisteredCbUbLlp.scala
  app/models/des/aboutthebusiness/PreviouslyRegisteredMLR.scala
  app/models/des/aboutthebusiness/PreviouslyRegisteredMLRView.scala
  app/models/des/aboutthebusiness/VATRegistration.scala
  app/models/des/businessactivities/BusinessActivitiesAll.scala
  app/models/fe/SubscriptionRequest.scala
  app/models/fe/SubscriptionView.scala
  app/models/fe/businessdetails/ActivityStartDate.scala
  app/models/fe/businessdetails/BusinessDetails.scala
  app/models/fe/businessdetails/ContactingYou.scala
  app/models/fe/businessdetails/CorporationTaxRegistered.scala
  app/models/fe/businessdetails/CorrespondenceAddress.scala
  app/models/fe/businessdetails/PreviouslyRegistered.scala
  app/models/fe/businessdetails/RegisteredOffice.scala
  app/models/fe/businessdetails/VATRegistered.scala
  release_notes/AMLS-4756.txt
  test/controllers/AmendVariationControllerSpec.scala
  test/controllers/SubscriptionControllerSpec.scala
  test/models/DefaultFEValues.scala
  test/models/des/SubscriptionRequestSpec.scala
  test/models/des/aboutthebusiness/AddressSpec.scala
  test/models/des/aboutthebusiness/BusinessContactDetailsSpec.scala
  test/models/des/aboutthebusiness/CorporationTaxRegisteredCbUbLlpSpec.scala
  test/models/des/aboutthebusiness/PreviouslyRegisteredSpec.scala
  test/models/des/aboutthebusiness/PreviouslyRegisteredViewSpec.scala
  test/models/des/aboutthebusiness/VATRegistrationSpec.scala
  test/models/fe/SubscriptionViewSpec.scala
  test/models/fe/businessdetails/ActivityStartDateSpec.scala
  test/models/fe/businessdetails/BusinessDetailsSpec.scala
  test/models/fe/businessdetails/ContactingYouSpec.scala
  test/models/fe/businessdetails/CorporationTaxRegisteredSpec.scala
  test/models/fe/businessdetails/CorrespondenceAddressSpec.scala
  test/models/fe/businessdetails/PreviouslyRegisteredSpec.scala
  test/models/fe/businessdetails/RegisteredOfficeSpec.scala
  test/models/fe/businessdetails/VATRegisteredSpec.scala
Labels: pending QA

#245 Release notes for release 4.125.0
  release_notes/releases/v4.125.0/v4.125.0-20-03-2019.txt
Labels: pending review
