Repository hmrc/amls, pull requests merged in 2019-04, with the labels that each got.

#233 Amls 4626
  app/models/fe/asp/Asp.scala
  app/models/fe/estateagentbusiness/EstateAgentBusiness.scala
  app/models/fe/moneyservicebusiness/MoneyServiceBusiness.scala
  app/models/fe/tcsp/Tcsp.scala
  app/services/AmendVariationService.scala
  release_notes/AMLS-4626.txt
  test/models/des/DesConstants.scala
  test/models/des/asp/AspSpec.scala
  test/models/fe/estateagentbusiness/EstateAgentBusinessSpec.scala
  test/models/fe/moneyservicebusiness/MoneyServiceBusinessSpec.scala
  test/models/fe/tcsp/TcspSpec.scala
Labels: pending QA

#247 Amls 4198
  app/models/des/businessactivities/TcspServicesOffered.scala
  app/models/des/tcsp/TcspTrustCompFormationAgt.scala
  app/models/fe/tcsp/ComplexCorpStructureCreation.scala
  app/models/fe/tcsp/OnlyOffTheShelfCompsSold.scala
  app/models/fe/tcsp/Tcsp.scala
  app/models/fe/tcsp/TcspTypes.scala
  release_notes/AMLS-4198.txt
  test/models/DefaultFEValues.scala
  test/models/des/tcsp/TcspAllSpec.scala
  test/models/des/tcsp/TcspTrustCompFormationAgtSpec.scala
  test/models/fe/tcsp/ComplexCorpStructureCreationSpec.scala
  test/models/fe/tcsp/OnlyOffTheShelfCompsSoldSpec.scala
  test/models/fe/tcsp/TcspSpec.scala
  test/models/fe/tcsp/TcspTypesSpec.scala
Labels: pending QA, reviewed

#248 Generated release notes for release 4.136.0
  release_notes/AMLS-4123.txt
  release_notes/releases/v4.136.0/v4.136.0-05-04-2019.txt
Labels: reviewed

#250 Update release notes to rmeove url
  generate-my-release-note.sh
  release_notes/AMLS-4198.txt
  release_notes/AMLS-4626.txt
  release_notes/AMLS-4892.txt
  release_notes/releases/v4.116.0/v4.116.0-21-02-2019.txt
  release_notes/releases/v4.119.0/v4.119.0-13-03-2019.txt
  release_notes/releases/v4.125.0/v4.125.0-20-03-2019.txt
  release_notes/releases/v4.136.0/v4.136.0-05-04-2019.txt
Labels: pending review

#252 Bug fix - TCSP section showing incomplete after user submits No to qu…
  app/models/fe/tcsp/ComplexCorpStructureCreation.scala
  app/models/fe/tcsp/OnlyOffTheShelfCompsSold.scala
  release_notes/AMLS-4952.txt
  test/models/des/DesConstants.scala
  test/models/fe/tcsp/ComplexCorpStructureCreationSpec.scala
  test/models/fe/tcsp/OnlyOffTheShelfCompsSoldSpec.scala
Labels: pending QA
